### ISSUE TITLE
Захардкоженный максимальный счёт...

### ISSUE THREAD

**Issue by bespoyasov** [open-tech-authors/solid#106]
...с неправильным значением.
<img width="666" alt="«Screenshot» 2019-06-01 at 19 18 41" src="https://user-images.githubusercontent.com/9102374/58751047-2b727300-84a2-11e9-8db2-6c55f9e65cc7.png">

**Comment by dex157** [comment]
Тадам ) но это просто фиксится, сделаю до понедельника

**Comment by dex157** [comment]
@bespoyasov готово, проверяй )
