### ISSUE TITLE
Подумать на дизайном меню

### ISSUE THREAD

**Issue by bespoyasov** [open-tech-authors/solid#12]

**Comment by bespoyasov** [comment]
Подумать над индикацией прогресса в меню. Как пример — next.js, слева отмеченные выделены зелёным.

**Comment by bespoyasov** [comment]
Next, кстати, тоже не особо парятся :–) 

У них есть главное меню, где показывается верхний уровень навигации, на котором отмечается прогресс зелёными буллитами:
<img width="301" alt="«Screenshot» 2019-03-14 at 19 17 46" src="https://user-images.githubusercontent.com/9102374/54377557-06821700-468e-11e9-87c1-a9bcfc690c39.png">

А есть доп. меню с очками на внутренних страницах:
<img width="438" alt="«Screenshot» 2019-03-14 at 19 17 50" src="https://user-images.githubusercontent.com/9102374/54377588-1568c980-468e-11e9-86ec-dd7a0e4f27ab.png">

Наши подсекции могут выполнять ту же роль, что их меню с очками. И даже больше, мы можем внутри открытой подсекции так же отмечать выполненные пункты.

**Comment by bespoyasov** [comment]
Пока что у меня идеи такие: 
- жирным выделяем текущую страницу;
- индикатор серый, если секция не пройдена;
- индикатор чёрный, если мы находимся в секции, и она не пройдена;
- индикатор слева зелёный, если секция пройдена.

Получатся вот такие кейсы:

1. Мы на странице «Примеры из идеального мира» внутри секции об SRP, секция пройдена не до конца:
<img width="313" alt="«Screenshot» 2019-03-14 at 19 48 08" src="https://user-images.githubusercontent.com/9102374/54379889-fc164c00-4692-11e9-8515-80cb2e5bc55a.png">

2. Мы внутри секции об SRP, она пройдена до конца:
<img width="305" alt="«Screenshot» 2019-03-14 at 19 49 16" src="https://user-images.githubusercontent.com/9102374/54379938-13edd000-4693-11e9-9deb-d9590f9acf3c.png">

3. Мы на странице введения. Пройдены секция введения и SRP:
<img width="315" alt="«Screenshot» 2019-03-14 at 19 50 07" src="https://user-images.githubusercontent.com/9102374/54379969-21a35580-4693-11e9-9d36-ed63fdadfe85.png">

Что думаешь? @dex157

**Comment by dex157** [comment]
Мне кажется все очень хорошо ) Ну тип, что тут можно дальше придумать:
- показывать в виде прогресса будет?
- делать прогресс подчёркиванием? 
- показывать прогресс дробью?

Нужно ли показывать прогресс подсекций в секциях? Вообще кажется что нет, человек заходит на сайт, и видит, что у него пройдены первые три секции, а 4ая серая, он смело смякает на 4-ую и видит прогресс в ней. Если хочет что то перепройти — перепроходит. В общем кажется твоё решение оптимально и достаточно )
