### ISSUE TITLE
Чем ниже?

### ISSUE THREAD

**Issue by pongo** [open-tech-authors/solid#136]
https://github.com/open-tech-authors/solid/blob/cafd49668c398b7612af1655253d696d7bf1a283/components/Quiz/quizzes/dip-intro-2/index.tsx#L19

> Чем ниже связность, тем выше сфокусирован модуль на конкретной задаче

Но ведь правильно будет: "чем выше связность"?

**Comment by bespoyasov** [comment]
Да, точно! Сделаешь пул, пожалуйста?
