### ISSUE TITLE
Информация о лицензии

### ISSUE THREAD

**Issue by mpstv** [open-tech-authors/solid#172]
Привет!

Не нашел нигде информации о том под какими лицензиями доступны контент и исходный код сайта.

**Comment by bespoyasov** [comment]
Привет!

Это правда, мы не думали о лицензии, когда релизили проект :–/

Сейчас сходу будет сложно разобраться, какая лицензия нужна — это надо будет поресёрчить. 

(По большому счёту нам достаточно указания авторства и ссылки на источник в плане контента и указания авторства в плане кода.)

**Comment by bespoyasov** [comment]
https://github.com/open-tech-authors/solid/commit/1cc66a109726bbe93849a1cf76a53e29fcaab56f
