### ISSUE TITLE
Подключить mobx-state-tree

### ISSUE THREAD

**Issue by dex157** [open-tech-authors/solid#18]

**Comment by bespoyasov** [comment]
Я обновил немного АПИ компонентов `QuizVariant` и `Quiz`: https://github.com/open-tech-authors/solid/pull/32

Вынес данные по тестам в `domain/quiz`, там внутри у каждого вопроса есть его название, варианты ответов с описаниями и проверка на правильный/неправильный.

Проверка лежит в контексте `QuizContext`, но оттуда надо будет поля `selected` перенести в другое место. Сейчас я их положил туда для простоты. Когда появится `state-tree`, они видимо, переползут в другой контекст.

**Comment by dex157** [comment]
Может быть мне в этой ветке подключать mobx-state-tree?

**Comment by bespoyasov** [comment]
Давай)
