### ISSUE TITLE
Описание патерна - Стратегия

### ISSUE THREAD

**Issue by Shramkoweb** [open-tech-authors/solid#189]
В теме https://ota-solid.vercel.app/srp/in-ideal-world мы используем класс `FormatSelector` который в свою очередь по сути является паттерном [Стратегия](https://refactoring.guru/ru/design-patterns/strategy)  и по сути реализуют логику выбора форматера. 

Хорошо было бы добавить в раздел https://ota-solid.vercel.app/srp/patterns обьяснение патерна ?

**Comment by bespoyasov** [comment]
Привет!

Стратегия описана в [списке шаблонов OCP](https://ota-solid.vercel.app/ocp/patterns). Пример там как раз ссылается на код из раздела об SRP.

Не уверен, что имеет смысл дублировать этот паттерн в SRP ещё раз или полностью переносить его в эту главу, но готов обсудить это 🙌

**Comment by Shramkoweb** [comment]
@bespoyasov аа понял, еще не дошел туда. 
Может и в разделе `SRP` тоже указать, что в этом месте мы используем `стратегию`, а что это такое - ми обсудим дальше [тут](https://ota-solid.vercel.app/ocp/patterns) ?

**Comment by bespoyasov** [comment]
Если получится это покрасивее вписать в текст, то я только за!

(Покрасивее — это одновременно ненавязчиво, без повторений, и чтобы с толку не сбивало из-за сломанного или перекрёстного повествования.)

Есть идеи, как это может выглядеть? 

У меня пока не получается придумать, как добавить упоминание, чтобы не переусложнить текст 😃

**Comment by Shramkoweb** [comment]
@bespoyasov https://github.com/open-tech-authors/solid/pull/190 добавил ПР. 
На мой взгляд вполне ок и не сбивает с толку.

**Comment by bespoyasov** [comment]
Вмёржил, спасибо! :–)
